### ISSUE TITLE
You say Excel only supports 65K points, this isn't quite true

### ISSUE THREAD

**Issue by bclehmann** [swharden/CsvPlot#1]
Since Excel 2007 this is no longer the case. Excel 2007+ support up to 2^20 rows (approximately 1 million)

Now a million points ain't great but it's a lot better than 65 thousand.

For reference, here is a graph with 100 000 points in Excel 2016:
![image](https://user-images.githubusercontent.com/8635304/87479825-6160b100-c5e9-11ea-901e-2dc5e1021bb1.png)

**Comment by swharden** [comment]
Good catch! I think in my head I was thinking of the low limit to the number of columns (16,384), but either way it was inaccurate so removing the claim fixed the readme. Thanks!

Excel specifications and limits:
https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
